lazywinadmin/AdsiPS

AdsiPS/Public/Get-ADSIOrganizationalUnit.ps1

I know..it's not a huge change..but it's the little things:
comment based help for DomainDistinguishedName.

Removed extra $ in the .PARAMETER

---

AdsiPS/Public/Get-ADSIFineGrainedPasswordPolicy.ps1
AdsiPS/Public/Get-ADSIObject.ps1
AdsiPS/Public/get-ADSIFGPasswordPolicies.ps1

Add a get-ADSIFGPasswordPolicies to retreive Fine Grained Policy

Add  get-ADSIFGPasswordPolicies function

---

AdsiPS/Public/Get-ADSISchema.ps1

Add Credential and ForestName Parameter to Get-ADSIPSSchema.

Solution of Issue13

---

AdsiPS/Public/Get-ADSIForest.ps1
AdsiPS/Public/Get-ADSISiteSubnet.ps1

Fix New-ADSIDirectoryContext ContextType

---

src/public/Get-ADSIDomainBackup.ps1

Add a function get-ADSIDomainBackup function to retrieve partition backup information
it's similar too repadmin /showbackup
It takes each naming context a retrieve the last change in the metadata attribute dsaSignature
It returns a pscustom object array

Add Active Directory partition info

---

src/public/Remove-ADSIGroupMember.ps1

Resolved #61 
Added message if member is not part of the group

Remove-ADSIGroupMember add return result

---

src/public/Copy-ADSIUserGroupMembership.ps1
src/public/Copy-ADSIUserGroupMemberships.ps1

First Part from #55 
Copy-ADSIComputerGroupMemberships will follow later.
If i made any mistake, please give me Feedback (My first function for a Powershell-Module).

New-Function - Copy-ADSIUserGroupMembership

---

src/public/Get-ADSIRIDinformation.ps1
src/public/Get-ADSIRIDsPool.ps1

Fixe: #90 
Changes : 
* Rename function to Get-ADSIRIDsPool
* Return data without using a variable
* add returned data in examples sections 
* use New-ADSIDirectoryContext

Improve Get-ADSIRIDInformation #90

---

src/public/Copy-ADSIGroupMembership.ps1

Added Computer Support to Copy-ADSIGroupMembership

---

src/public/Get-ADSIGroupMembershipTreeView.ps1

Function to get all Group Memberships of a User or Computer including all Groups inherited by another group in a Tree View in Active Directory

New-Function Group membership tree view

---

src/public/Copy-ADSIGroupMembership.ps1
src/public/Get-ADSIGroupMembershipTreeView.ps1

Update TreeView and copy

---

src/public/Get-ADSIComputer.ps1

Add position to Identity parameter of Get-ADSIComputer function

---

src/public/Get-ADSIPrincipalGroupMembership.ps1
src/public/Get-ADSIUser.ps1

Fix for issue #98 
Allows users to retrieve group membership for computers.

Fix Issue #98

---

src/source.psd1

This is already present in the psm1

Remove RequiredAssembly

---

src/public/Set-ADSIComputer.ps1

New Function Set-ADSIComputer

---

src/public/Set-ADSIGroup.ps1

New Function Set-ADSIGroup

---

src/public/New-ADSIUser.ps1
src/public/Set-ADSIUser.ps1

Implement AccountExpiration on New-ADSIUser & Set-ADSIUser

---

src/public/Compare-ADSITeamGroups.ps1
src/public/Disable-ADSIComputer.ps1
src/public/Disable-ADSIUser.ps1
src/public/Enable-ADSIComputer.ps1
src/public/Enable-ADSIUser.ps1
src/public/Get-ADSIComputer.ps1
src/public/Get-ADSIDomain.ps1
src/public/Get-ADSIDomainController.ps1

Add Verbose message to some functions

Add Some Verbose Message

---

src/public/Remove-ADSIComputer.ps1
src/public/Remove-ADSIGroup.ps1
src/public/Remove-ADSISite.ps1
src/public/Remove-ADSISiteSubnet.ps1
src/public/Remove-ADSIUser.ps1
src/public/Reset-ADSIUserPasswordAge.ps1
src/public/Set-ADSIComputer.ps1
src/public/Set-ADSIGroup.ps1
src/public/Set-ADSIUser.ps1
src/public/Set-ADSIUserPassword.ps1
src/public/Test-ADSICredential.ps1
src/public/Test-ADSIUserIsGroupMember.ps1
src/public/Test-ADSIUserIsLockedOut.ps1
src/public/Unlock-ADSIComputer.ps1
src/public/Unlock-ADSIUser.ps1

Added some Verbose Messages & reworked some function to "fit the usual format" and Pipeline support

Function Reworks & More Verbose Message

---

CONTRIBUTING.md
README.md
docs/doc_usecases.md

* Simplify Readme
* Move docs into separated md files
* Update Contributions page

Update documentation !deploy

---

build/requirements.psd1
build/tasks.build.ps1

* Force using Pester 4.10.0 instead of latest

update pester dependencies
